### ISSUE TITLE
email-body and Payload delivery is an invalid combination

### ISSUE THREAD

**Issue by carnak** [MISP/mail_to_misp#2] opened 2017-06-01 18:35 UTC
Hello - I am getting following stack trace when attempting to run mail_to_misp:

Jun  1 01:16:55 minemeld postfix/smtpd[3694]: connect from <redacted>.com[1.2.3.4]
Jun  1 01:16:55 minemeld postfix/smtpd[3694]: ADB6E1B7197: client=<redacted>.com[1.2.3.4]
Jun  1 01:16:55 minemeld postfix/cleanup[3702]: ADB6E1B7197: message-id=<BY1PR0701MB1189C6E756AD39CAB92940F8F5F60@BY1PR0701MB1189.namprd07.prod.outlook.com>
Jun  1 01:16:55 minemeld postfix/qmgr[38096]: ADB6E1B7197: from=<prvs=318f4e478=alan@dayjob.com>, size=150947, nrcpt=1 (queue active)
Jun  1 01:16:56 minemeld postfix/local[3703]: ADB6E1B7197: to=<misp_handler@<redacted>.eastus.cloudapp.azure.com>, relay=local, delay=1.1, delays=0.32/0/0/0.76, dsn=5.3.0, status=bounced (Command died with status 1: "/usr/src/mail_to_misp/mail_to_misp.py". Command output: /usr/local/lib/python3.5/dist-packages/urllib3-1.21.1-py3.5.egg/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning) /usr/local/lib/python3.5/dist-packages/pymisp-2.4.71-py3.5.egg/pymisp/api.py:1483: DeprecationWarning: Call to deprecated function add_tag.   def add_tag(self, event, tag, attribute=False): Traceback (most recent call last):   File "/usr/src/mail_to_misp/mail_to_misp.py", line 141, in <module>     misp.add_named_attribute(new_event, 'email-body', original_email_data, category='Payload delivery', to_ids=False)   File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.71-py3.5.egg/pymisp/api.py", line 436, in add_named_attribute     attributes.append(self._prepare_full_attribute(category, type_value, value, to_ids, comment, distribution, **kwargs))   File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.71-py3.5.egg/pymisp/api.py", line 257, in _prepare_full_attribute     to_ids=to_ids, comment=comment, distribution=distribution, **kwargs)   File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.71-py3.5.egg/pymisp/mispevent.py", line 122, in set_all_values     raise NewAttributeError('{} and {} is an invalid combinaison, type for this category has to be in {}'.format(kwargs.get('type'), kwargs.get('category'), (', '.join(self.category_type_mapping[kwargs['category']])))) pymisp.exceptions.NewAttributeError: email-body and Payload delivery is an invalid combinaison, type for this category has to be in md5, sha1, sha224, sha256, sha384, sha512, sha512/224, sha512/256, ssdeep, imphash, impfuzzy, authentihash, pehash, tlsh, filename, fi
Jun  1 01:16:56 minemeld postfix/cleanup[3702]: BAB671B71D7: message-id=<20170601011656.BAB671B71D7@<redacted>.eastus.cloudapp.azure.com>
Jun  1 01:16:56 minemeld postfix/qmgr[38096]: BAB671B71D7: from=<>, size=14435, nrcpt=1 (queue active)
Jun  1 01:16:56 minemeld postfix/bounce[3708]: ADB6E1B7197: sender non-delivery notification: BAB671B71D7
Jun  1 01:16:56 minemeld postfix/qmgr[38096]: ADB6E1B7197: removed

Please advise if this is something that can be mitigated.

Thanks!

**Comment by rommelfs** [comment] 2017-06-02 05:54
Hi,

It appears that you are not running the latest MISP version (from git) which has support for email-body in category 'Payload delivery'. If you can't upgrade MISP right now, it *should* be possible to bypass the creation of the email message in MISP by setting the following in the config:
`attach_original_mail = False`

Hope this helps!

**Comment by rommelfs** [comment] 2017-06-02 07:16
We've also corrected the spelling mistake ('combinaison') ;)

**Comment by carnak** [comment] 2017-06-02 10:55
Many thanks for response!  I have tried as you suggest, but am getting following error message:

/0/0/1, dsn=5.3.0, status=bounced (Command died with status 1: "/usr/src/mail_to_misp/mail_to_misp.py". Command output: /usr/local/lib/python3.5/dist-packages/urllib3-1.21.1-py3.5.egg/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings   InsecureRequestWarning) /usr/local/lib/python3.5/dist-packages/pymisp-2.4.71-py3.5.egg/pymisp/api.py:1483: DeprecationWarning: Call to deprecated function add_tag.   def add_tag(self, event, tag, attribute=False): Traceback (most recent call last):   File "/usr/src/mail_to_misp/mail_to_misp.py", line 151, in <module>     email_data = email_data.split(stopword, 1)[0] TypeError: Can't convert 'bytes' object to str implicitly )

I also am not able to update after doing a "git stash", as it complains about other changes that I don't know how to resolve.

So, after all that being said, I now know what I will be doing this weekend, i.e., building a new MISP instance :)

Thanks!!!

**Comment by rommelfs** [comment] 2017-06-02 13:29
Please make sure you are running the latest version since many changes have happened, also the config has changed slightly. If it still doesn't work after upgrading (also the config file), please show the config at the given position ('stopword')

**Comment by rommelfs** [comment] 2017-06-04 12:59
part one of the issue is solved, for the second an individual issue has been opened -> closing.

**Closed by rommelfs** 2017-06-04 12:59 UTC

**Comment by carnak** [comment] 2017-06-04 17:45
Hello - Sorry to see this closed already.  Attached is the report on my config.  This MISP instance was built from scratch 2 days ago, using the latest source available at that time.  One thing to note is that the email reports are creating events in the MISP system, but the IoC parsing is not occurring.  Another thing to note is that the remote MTA is not currently  happy with the reputation of my MISP MTA:

Jun  4 10:29:21 misp postfix/smtp[31021]: 64B2D413DE: host blackagar.com[5.1.6.7] refused to talk to me: 554-blackagar.com 554 Your access to this mail system has been rejected due to the sending MTA's poor reputation. If you believe that this failure is in error, please contact the intended recipient via alternate means.


[MISP.report.json.txt](https://github.com/MISP/mail_to_misp/files/1050573/MISP.report.json.txt)

**Comment by rommelfs** [comment] 2017-06-04 19:31
The issue about non-parsing of IoCs is being handled in issue #3. The exception you describe is happening very early just after the event creation. I suspect a configuration file issue. That's why I asked for this in #3. 

The reputation of your sending server's IP address or other indicators why this mail server's messages are rejected are hard to evaluate based on the current facts. If you believe this has to do with mail_to_misp or MISP, please create a separate issue where you think it fits best into (mail_to_misp is by default not sending mails at all).

**Comment by carnak** [comment] 2017-06-04 19:52
Hello Sascha - my apologies for not having sent the config file to you yet, but I simply don't understand exactly what file you want to see. Please advise filename(s), and I will get them to you asap

Thanks!
Alan
